config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  get 'host' , to: 'pages#host'
  get 'terms' , to: 'pages#terms'
  get '/terms/privacy_policy' , to: 'pages#privacy'
  get '/terms/nondiscrimination_policy' , to: 'pages#nondiscrimination'
  get '/terms/payments_terms' , to: 'pages#payments'
  get '/terms/host_guarantee' , to: 'pages#host_guarantee'
  get '/terms/guest_refund_policy' , to: 'pages#guest_refund'
  get '/terms/copyright_policy' , to: 'pages#copyright'
  get '/terms/cookie_policy' , to: 'pages#cookie'
  get '/terms/guest_waiver' , to: 'pages#guest_waiver'

  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
  
  resources :users, only: [:show] do
    member do
      post '/verify_phone_number' => 'users#verify_phone_number'
      patch '/update_phone_number' => 'users#update_phone_number'
    end
  end
  
  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
    resources :calendars
  end 
  
  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]
  
  get '/your_bookings' => 'reservations#your_bookings'
  get '/your_reservations' => 'reservations#your_reservations'
  
  get 'search' => 'pages#search'
  
  get 'dashboard' => 'dashboards#index'
  
  resources :reservations, only: [:approve, :decline] do
    member do
      post '/approve' => "reservations#approve"
      post '/decline' => "reservations#decline"
    end
  end
  
  resources :revenues, only: [:index]
  
  resources :conversations, only: [:index, :create]  do
    resources :messages, only: [:index, :create]
  end
  
  get '/host_calendar' => "calendars#host"
  get '/payment_method' => "users#payment"
  get '/payout_method' => "users#payout"
  post '/add_card' => "users#add_card"
  
  get '/notification_settings' => 'settings#edit'
  post '/notification_settings' => 'settings#update'
  
  get '/notifications' => 'notifications#index'
  
  mount ActionCable.server => '/cable'
  
end

app/models/room.rb
class Room < ApplicationRecord
  enum instant: {Request: 0, Instant: 1}
  
  belongs_to :user
  has_many :photos
  has_many :reservations
  
  has_many :guest_reviews
  has_many :calendars
  
  validates :room_type, presence: true
  
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  
  def cover_photo(size)
    if self.photos.length > 0
      self.photos[0].image.url(size)
    else
      "blank.jpg"
    end
  end
  
  def average_rating
    guest_reviews.count == 0 ? 0 : guest_reviews.average(:star).round(2).to_i
  end
end

app/controllers/room_controller.rb
class RoomController < ApplicationController
  before_action :set_room, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  
  def index
    @rooms = current_user.rooms
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to listing_room_path(@room), notice: "Saved..."
    else
      flash[:alert] = "Something went wrong..."
      render :new
    end
  end
  
  def show
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
  end

  def amenities
  end

  def location
  end

  def update
    if @room.update(new_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Something went wrong..."
    end
    redirect_back(fallback_location: request.referer)
  end
  
  private
    def set_room
      @room = Room.find(params[:id])
    end
  
    def room_params
      params.require(:room).permit(:room_type, :listing_name, :summary, :address, :is_internet, :is_lounge, :is_pool, :is_shower, :is_towel, :is_yoga, :is_cycling, :is_pilates, :is_basketball, :is_childcare, :is_weights, :is_boxing, :price, :active)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :is_authorised, only: [:listing, :pricing, :description, :photo_upload, :amenities, :location, :update]
  
  def index
    @rooms = current_user.rooms
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    if !current_user.is_active_host
      return redirect_to payout_method_path, alert: "Please Connect to Stripe Express first."
    end
    
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to listing_room_path(@room), notice: "Saved..."
    else
      flash[:alert] = "Something went wrong..."
      render :new
    end
  end
  
  def show
    @photos = @room.photos
    @guest_reviews = @room.guest_reviews
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
    @photos = @room.photos
  end

  def amenities
  end

  def location
  end

  def update
    
    new_params = room_params
    new_params = room_params.merge(active: true) if is_ready_room
    
    if @room.update(new_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Something went wrong..."
    end
    redirect_back(fallback_location: request.referer)
  end
  
  # --- Reservations ---
  def preload
    today = Date.today
    unavailable_dates = @room.calendars.where("status = ? AND day > ?", 1, today)
    special_dates = @room.calendars.where("status = ? AND day > ? AND price <> ?",0, today, @room.price)

    render json: {
        unavailable_dates: unavailable_dates,
        special_dates: special_dates
    }
  end

  def preview
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    output = {
      conflict: is_conflict(start_date, end_date, @room)
    }

    render json: output
  end
  
  private
    def is_conflict(start_date, end_date, room)
      check = room.calendars.where("day BETWEEN ? AND ? AND status = ?", start_date, end_date, 1).limit(1)

      check.size > 0? true : false
    end
  
    def set_room
      @room = Room.find(params[:id])
    end
  
    def is_authorised
      redirect_to root_path, alert: "You don't have permission" unless current_user.id == @room.user_id
    end
  
    def is_ready_room
      !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank?
    end
  
    def room_params
      params.require(:room).permit(:room_type, :listing_name, :summary, :address, :is_internet, :is_lounge, :is_pool, :is_shower, :is_towel, :is_yoga, :is_cycling, :is_pilates, :is_basketball, :is_childcare, :is_weights, :is_boxing, :price, :active, :instant)
    end
end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/rooms/_room_menu.html.erb
<ul class="sidebar">
  <li>
    <%= link_to "Listing", listing_room_path, class: "sidebar-link" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li>
    <%= link_to "Pricing", pricing_room_path, class: "sidebar-link" %>
    <% if !@room.price.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li>
    <%= link_to "Description", description_room_path, class: "sidebar-link" %>
    <% if !@room.listing_name.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li>
    <%= link_to "Photos", photo_upload_room_path, class: "sidebar-link" %>
    <% if !@room.photos.blank? %>
      <span id="photo_check" class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li>
    <%= link_to "Amenities", amenities_room_path, class: "sidebar-link" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li>
    <%= link_to "Location", location_room_path, class: "sidebar-link" %>
    <% if !@room.address.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
</ul>


<hr/>

<% is_ready = !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank? %>

<%= form_for @room do |f| %>
  <%= f.hidden_field :active, value: true %>
  <%= f.submit "Publish", id: "publish_button", class: "btn btn-new btn-block", disabled: !is_ready %>
<% end %>

app/views/rooms/_rooms_list.html.erb
<% rooms.each do |room| %>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading preview">
          <%= image_tag room.cover_photo(:medium) %>
        </div>
        <div class="panel-body">
          <%= link_to room.listing_name, room %><br/>
          $<%= room.price %> - <%= room.room_type %>
          <div id="star_<%= room.id %>"></div> <%= pluralize(room.guest_reviews.count, "review") %>
        </div>
      </div>
    </div>

    <script>
      $('#star_<%= room.id %>').raty({
        path: '/assets',
        readOnly: true,
        score: <%= room.average_rating %>
      });
    </script>
<% end %>

app/views/rooms/amenities.html.erb
<div class="container content">
  <div class="row">
    <div class="col-md-3 col-lg-3">
      <div class="card d-md-block d-lg-block mb-4">
        <div class="card-body">
          <div class="container">
            <%= render 'room_menu' %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <div class="card d-md-block d-lg-block mb-4">
        <div class="card-body">
          <div class="container">
            <%= form_for @room do |f| %>
              <label>Amenities</label>
              <div class="row form-group">
              <div class="col-md-4">
                <%= f.check_box :is_weights %> Free weights / Machines
              </div>
              <div class="col-md-4">
                <%= f.check_box :is_lounge %> Lounge
              </div>
              <div class="col-md-4">
                <%= f.check_box :is_shower %> Shower
              </div>
            </div>

            <div class="row form-group">
              <div class="col-md-4">
                <%= f.check_box :is_towel %> Towel Service
              </div>
              <div class="col-md-4">
                <%= f.check_box :is_yoga %> Yoga equipment
              </div>
              <div class="col-md-4">
                <%= f.check_box :is_cycling %> Spin Bikes Available
              </div>
            </div>
            
            <div class="row form-group">
              <div class="col-md-4">
                <%= f.check_box :is_pilates %> Pilates equipment
              </div>
              <div class="col-md-4">
                <%= f.check_box :is_pool %> Swimming Pool
              </div>
              <div class="col-md-4">
                <%= f.check_box :is_basketball %> Basketball Court
              </div>
            </div>
            
            <div class="row form-group">
              <div class="col-md-4">
                <%= f.check_box :is_childcare %> Childcare available
              </div>
              <div class="col-md-4">
                <%= f.check_box :is_internet %> Internet
              </div>
              <div class="col-md-4">
                <%= f.check_box :is_boxing %> Boxing equipment
              </div>
            </div>
            <br/><br/>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-new" %>
            </div>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/create.html.erb
<h1>Room#create</h1>
<p>Find me in app/views/room/create.html.erb</p>

app/views/rooms/description.html.erb
<div class="container content">
  <div class="row">
    <div class="col-md-3 col-lg-3">
      <div class="card d-md-block d-lg-block mb-4">
        <div class="card-body">
          <div class="container">
            <%= render 'room_menu' %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <div class="card d-md-block d-lg-block mb-4">
        <div class="card-body">
          <div class="container">
          <%= form_for @room do |f| %>

            <div class="row">
              <div class="form-group">
              <label>Listing name</label>
                <%= f.text_field :listing_name, placeholder: "What is your listing name?", class: "form-control", required: true %>
              </div>
            </div>

            <div class="row">
              <div class="form-group">
              <label>Summary</label>
                <%= f.text_area :summary, rows: 5, placeholder: "Tell us about your gym.", class: "form-control", required: true %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-new" %>
            <% end %>

          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="container content">
  <div class="container pt-4 pb-5">
    <div class="row">
      <div class="col-md-3 col-lg-3">
        <div class="card d-md-block d-lg-block mb-4">
          <div class="card-body">
          <ul class="sidebar">
          <li><%= link_to "Listings", rooms_path, class: "sidebar-link active" %></li>
          <li class="sidebar-item"><%= link_to "Reservations", your_reservations_path, class: "sidebar-link" %></li>
          <li class="sidebar-item"><%= link_to "Your Bookings", your_bookings_path, class: "sidebar-link" %></li>
          </ul>
          </div>
        </div>
      </div>
    <% if @rooms.count > 0 %>
      <div class="col-md-9">
        <div class="card d-md-block d-lg-block mb-4">
          <div class="card-body">
            <div class="container">
              <label><h2>Listings</h2></label>
              <% @rooms.each do |room| %>
              <div class="row">
              <div class="col-md-2">
                <%= image_tag room.cover_photo(:thumb) %>
              </div>
              <div class="col-md-7">
                <h4><%= room.listing_name %></h4>
              </div>
              <div class="col-md-3 right">
                <%= link_to "Update", listing_room_path(room), class: "btn btn-new" %>
              </div>
              </div>
              <hr/>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <div class="col-md-6 text-center">
        <h1>You don't have any listings.</h1>
        <a href="/rooms/new" role="button" class="text-babu">
          <i class="fa fa-plus-circle fa-3x"></i>
        </a>
      </div>
    <% end %>
    </div>
  </div>
</div>
    

app/views/rooms/listing.html.erb
<div class="container content">
  <div class="row">
    <div class="col-md-3 col-lg-3">
      <div class="card d-md-block d-lg-block mb-4">
        <div class="card-body">
          <%= render 'room_menu' %>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <div class="card d-md-block d-lg-block mb-4">
        <div class="card-body">
          <div class="container">
            <%= form_for @room do |f| %>

              <div class="row">
                <div class="col-md-4 select">
                  <div class="form-group">
                    <label>Gym Type</label>
                    <%= f.select :room_type, [["Fitness Center", "Fitness Center"], ["Crossfit Gym", "Crossfit Gym"], ["Studio", "Studio"], ["Sports Training", "Sports Training"]],
                                  id: "room_type", prompt: "Select...", class: "form-control" %>
                  </div>
                </div>
                
                <div class="col-md-4 select">
                  <div class="form-group">
                    <label>Booking Type</label>
                    <%= f.select :instant, Room.instants.map {|key,value| [key.humanize, key]}, prompt: "Select...", class: "form-control" %>
                  </div>
                </div>
              
              </div>
              <div><%= f.submit "Save", class: "btn btn-new" %></div>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/location.html.erb
<div class="container content">
  <div class="row">
    <div class="col-md-3 col-lg-3">
      <div class="card d-md-block d-lg-block mb-4">
        <div class="card-body">
          <div class="container">
            <%= render 'room_menu' %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <div class="card d-md-block d-lg-block mb-4">
        <div class="card-body">
          <div class="container">
            <%= form_for @room do |f| %>

              <div class="row">
                <div class="form-group">
                  <label>Location</label>
                  <%= f.text_field :address, placeholder: "What is your address?", class: "form-control", required: true, id: "autoaddress" %>
                </div>
              </div>

              <div class="text-center">
                <%= f.submit "Save", class: "btn btn-new" %>
              </div>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="container content">
  <div class="row">
    <div class="col-lg-3">
      <div class="alert alert-warning alert-dismissible d-none d-lg-block" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <span class="alert-link"></span> This is the very beginning of your Listing!
      </div>
    </div>
    <div class="col-lg-9">
      <div class="card d-md-block d-lg-block mb-4">
        <div class="card-body">
          <div class="container">
            <%= form_for @room do |f| %>

              <div class="row">
                <div class="col-md-4 select">
                  <div class="form-group">
                    <label>Gym Type</label>
                    <%= f.select :room_type, [["Fitness Center", "Fitness Center"], ["Crossfit Box", "Crossfit Box"], ["Studio", "Studio"], ["Sports Training", "Sports Training"]],
                                  id: "room_type", prompt: "Select...", class: "form-control" %>
                  </div>
                </div>
                  
                <div class="col-md-4 select">
                  <div class="form-group">
                    <label>Booking Type</label>
                    <%= f.select :instant, Room.instants.map {|key,value| [key.humanize, key]}, selected: 'Instant', prompt: "Select...", class: "form-control" %>
                  </div>
                </div>
               
              </div>
              <div><%= f.submit "Create Listing", class: "btn btn-new" %></div>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/photo_upload.html.erb
<div class="container content">
  <div class="row">
    <div class="col-md-3 col-lg-3">
      <div class="card d-md-block d-lg-block mb-4">
        <div class="card-body">
          <div class="container">
            <%= render 'room_menu' %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="container">
          <label>Photos</label>
          <br>
          <div class="row">
            <div class="col-md-offset-3 col-md-6">
              <!-- PHOTOS UPLOAD GOES HERE -->
              
              <%= form_for @room, url: room_photos_path(@room), method: 'post', html: {multipart: true} do |f| %>
                <div class="row">
                  <div class="form-group">
                    <span class="btn btn-file text-babu">
                      <i class="fa fa-cloud-upload" aria-hidden="true"></i> Select Photos
                      <%= file_field_tag "images[]", type: :file, multiple: true %>
                    </span>
                  </div>
                </div>

                <div class="text-center">
                  <%= f.submit "Add Photos", class: "btn btn-new" %>
                </div>

              <% end %>
            </div>
          </div>

          <div id="photos"><%= render 'photos/photos_list' %></div>
        </div>
      </div>

    </div>
    </div>
  </div>
</div>

app/views/rooms/pricing.html.erb
<div class="container content">
  <div class="row">
    <div class="col-md-3 col-lg-3">
      <div class="card d-md-block d-lg-block mb-4">
        <div class="card-body">
          <div class="container">
            <%= render 'room_menu' %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <div class="card d-md-block d-lg-block mb-4">
        <div class="card-body">
          <div class="container">
            <%= form_for @room do |f| %>

              <div class="row">
                <div class="form-group">
                  <label>Price</label>
                  <%= f.text_field :price, placeholder: "Set your daily price. e.g. 60", class: "form-control", required: true %>
                </div>
              </div>

              <div class="text-center">
                <%= f.submit "Save", class: "btn btn-new" %>
              </div>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<!-- Image -->
<div class="container pt-4 pb-5">
  <div class="row">
    <div class="col-md-12">
      <div class="container">
        <br>
        <%= image_tag @room.cover_photo(nil), width: "100%" %>
      </div>
      <div class="container">
        <div class="row">

          <!-- LEFT PANEL -->
          <div class="col-md-8">

            <!-- Listing Name -->
            <div class="row">
              <div class="col-md-8">
                <h1><%= @room.listing_name %></h1>
                <%= @room.address %>
              </div>
              <div class="col-md-4 text-center">
                <br>
                <% if !@room.user.avatar.blank? %>
                  <%= image_tag(@room.user.avatar.url(:thumb), class: "img-circle avatar-large") %>
                <% else %>
                  <%= image_tag("missing.png", class: "card-profile-img")  %>
                <% end %>
                <br/><br/>
                <%= link_to user_path(@room.user) do %>
                  <%= @room.user.fullname %>
              <% end %>
              </div>
            </div>
            <hr/>

            <!-- Room Info -->
            <div class="row text-babu">
              <div class="row text-center row-space-1">
                <div class="col-md-3">
                  <i class="fa fa-building-o fa-2x"></i>
                </div>
              </div>

              <div class="row text-center">
                <div class="col-md-3"><%= @room.room_type %></div>
              </div>

            </div>
            <hr/>

            <!-- About -->
            <div class="row">
              <div class="col-md-12">
                <h3>About This Listing</h3>
                <p><%= @room.summary %></p>
              </div>
            </div>
            <hr/>

            <!-- Amenities -->
            <div class="row">
              <div class="col-md-3">
                <h3>Amenities</h3>
              </div>

              <div class="col-md-9">
                <div class="row">
                  <div class="col-md-6">
                    <ul class="amenities">
                      <li class="<%= 'text-line-through' if !@room.is_weights %>">Free Weights</li>
                      <li class="<%= 'text-line-through' if !@room.is_shower %>">Shower</li>
                      <li class="<%= 'text-line-through' if !@room.is_towel %>">Towel Service</li>
                    </ul>
                  </div>
                  <div class="col-md-6">
                    <ul class="amenities">
                      <li class="<%= 'text-line-through' if !@room.is_yoga %>">Yoga equipment</li>
                      <li class="<%= 'text-line-through' if !@room.is_cycling %>">Cycling</li>
                      <li class="<%= 'text-line-through' if !@room.is_boxing %>">Boxing equipment</li>
                    </ul>
                  </div>

                </div>
                <div class="row">
                  <div class="col-md-6">
                    <ul class="amenities">
                      <li class="<%= 'text-line-through' if !@room.is_pilates %>">Pilates equipment</li>
                      <li class="<%= 'text-line-through' if !@room.is_pool %>">Swimming pool</li>
                      <li class="<%= 'text-line-through' if !@room.is_basketball %>">Basketball court</li>
                    </ul>
                  </div>
                  <div class="col-md-6">
                    <ul class="amenities">
                      <li class="<%= 'text-line-through' if !@room.is_internet %>">Internet</li>
                      <li class="<%= 'text-line-through' if !@room.is_lounge %>">Lounge</li>
                      <li class="<%= 'text-line-through' if !@room.is_childcare %>">Childcare</li>
                    </ul>
                  </div>

                </div>
              </div>

            </div>
            <hr/>

            <!-- Carousel -->
              <div class="row">

                <% if @photos.length > 0 %>
                  <div id="myCarousel" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                      <% @photos.each do |photo| %>
                          <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
                      <% end %>
                    </ol>

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner">
                      <% @photos.each do |photo| %>
                          <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                            <%= image_tag photo.image.url() %>
                          </div>
                      <% end %>
                    </div>

                    <!-- Left and right controls -->
                    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                      <span class="glyphicon glyphicon-chevron-left"></span>
                      <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#myCarousel" data-slide="next">
                      <span class="glyphicon glyphicon-chevron-right"></span>
                      <span class="sr-only">Next</span>
                    </a>
                  </div>
                <% end %>

              </div>
            <hr/>

            <!-- GOOGLE MAP -->
            <div class="row">

              <div id="map" style="width: 100%; height: 400px"></div>

              <script src="https://maps.googleapis.com/maps/api/js"></script>
              <script>
                  function initialize() {
                    var location = {lat: <%= @room.latitude %>, lng: <%= @room.longitude %>};
                    var map = new google.maps.Map(document.getElementById('map'), {
                      center: location,
                      zoom: 14
                    });

                    var marker = new google.maps.Marker({
                      position: location,
                      map: map
                    });

                    var infoWindow = new google.maps.InfoWindow({
                      content: '<div id="content"><%= image_tag @room.cover_photo(:medium) %></div>'
                    });

                    infoWindow.open(map, marker);
                  }

                  google.maps.event.addDomListener(window, 'load', initialize);
              </script>

            </div>
            <hr/>

            <!-- NEAR BY ROOMS -->
              <div class="row">
                <h3>Nearby</h3>
                <br>
                <% for room in @room.nearbys(5).max(6).shuffle %>
                    <div class="col-md-4">
                      <div class="panel panel-default">
                        <div class="panel-heading preview">
                          <%= image_tag room.cover_photo(:medium) %>
                        </div>
                        <div class="panel-body">
                          <%= link_to room.listing_name, room %><br/>
                          (<%= room.distance.round(2) %> miles away)
                        </div>
                      </div>
                    </div>
                <% end %>
              </div>

            <!-- REVIEWS -->
            <div class="row">
              <div class="col-md-12">
                <h3>
                  <%= pluralize(@guest_reviews.count, "Review") %> &nbsp;
                  <span id="average_rating"></span>
                </h3>
                <div class="container">
                  <div><%= render "reviews/guest_list" %></div>
                </div>
              </div>
            </div>
            <br/>
            <hr/>

          </div>


          <!-- RIGHT PANEL -->
          <div class="col-md-4">
            <br>
            <%= render 'reservations/form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<br>

<script>
  $('#average_rating').raty({
    path: '/assets',
    readOnly: true,
    score: <%= @room.average_rating %>
  });
</script>

app/views/rooms/update.html.erb
<h1>Room#update</h1>
<p>Find me in app/views/room/update.html.erb</p>